### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Linear1024** [Dimsmary/Ossas_ChatBot#10]
前几次打开ossas都正常，加入了新的聊天记录后一打开什么都不显示就闪退

**Comment by Dimsmary** [comment]
请用控制台运行程序，截图报错后上传。
在模型生成后，再次添加聊天记录是不会被应用的，详情请看readme [使用方法>OSSAS] 结尾处。

**Comment by wulvjun** [comment]
Traceback (most recent call last):
  File "main.py", line 108, in <module>
  File "Seq2Seq.py", line 305, in pre_precess
  File "Seq2Seq.py", line 27, in padding_sign
AttributeError: 'numpy.ndarray' object has no attribute 'append'
[5788] Failed to execute script main

**Comment by Linear1024** [comment]
Failed to write all bytes for _pywrap_tensorflow_internal.pyd
fwrite: No space left on device
