### ISSUE TITLE
OSSAS.exe闪退

### ISSUE THREAD

**Issue by Steven-Chang1114** [Dimsmary/Ossas_ChatBot#14]
错误如下

```
c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:489: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 296, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "Seq2Seq.py", line 8, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\__init__.py", line 40, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 296, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: 找不到指定的模块。


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[8432] Failed to execute script main
```
我之前还试着安装过requirement.txt，但是还是会打开OSSAS.exe之后黑一段时间然后突然报错加闪退，QQRecord2Excel.exe倒可以运行。
顺便请问一下这个程序是只要是win电脑就能打开还是说也得安装相应插件和lib，感谢

**Comment by Dimsmary** [comment]
类似问题已存在：[issue#4](https://github.com/Dimsmary/Ossas_ChatBot/issues/4)

**Comment by Steven-Chang1114** [comment]
感谢！问题已解决！
我想再请问一下是否下载完的OSSAS.exe就已经存在一个训练过的模型，还是说我们得先训练一次模型才能再成功运行模式4
目前报错如下
```
-----------------
输入工作模式：4
输入数字0 退出
你说：你好
Traceback (most recent call last):
  File "main.py", line 124, in <module>
  File "Seq2Seq.py", line 221, in predict
  File "Seq2Seq.py", line 86, in get_dict
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OSS\\Ossas\\workspace\\train_data\\words_dictionary.txt'
[10764] Failed to execute script main
```
我之前没有导入过自己的训练数据，直接就运行下载的exe文件

我没有在文档里看到关于words_dictionary.txt的描述，但是上面写启动程序前train.xlsx需准备好，请问在运行OSSAS.exe前我是否得先导入自己的训练数据来生成和训练这个模型然后当我有train.xlsx并且train_data文件夹里存在words_dictionary.txt时方可成功运行？

**Comment by Dimsmary** [comment]
已下载的文件不包括训练好的模型，需要自行准备语料进行训练。
