### ISSUE TITLE
黑屏然后闪退

### ISSUE THREAD

**Issue by ghost** [Dimsmary/Ossas_ChatBot#15]
运行ossas.exe后黑屏，一段时间后显示以下文字：

> c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:489: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 296, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "Seq2Seq.py", line 8, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\__init__.py", line 40, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 296, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[11552] Failed to execute script main

运行main.py的反馈是：

> Traceback (most recent call last):
  File "F:\Ossas_ChatBox\Ossas_ChatBot-master\main.py", line 5, in <module>
    import Seq2Seq as rnn
  File "F:\Ossas_ChatBox\Ossas_ChatBot-master\Seq2Seq.py", line 8, in <module>
    from tensorflow.keras.preprocessing.text import Tokenizer
ModuleNotFoundError: No module named 'tensorflow'

requirements.txt里的东西都装了

**Comment by Dimsmary** [comment]
对于tensorflow初始化失败问题：
[issue#4](https://github.com/Dimsmary/Ossas_ChatBot/issues/4)

对于运行main.py后的问题：
ModuleNotFoundError: No module named 'tensorflow'
你并没有安装tensorflow
