### ISSUE TITLE
[功能请求]QQRecord2Excel处理数据时增加出错行数通知

### ISSUE THREAD

**Issue by zhenchao** [Dimsmary/Ossas_ChatBot#19]
我是自行编辑训练数据的（~~找沙雕群友当苦力~~）
希望能增加一个提示表格处理出错行数的功能。

使用模式2转换record.xlsx到soft_record.xlsx时报错。
问题似乎是因为表格一些地方不符合要求，截取前数十条数据时可以正常处理。
我这边一共有7w+条数据，因为是打算群里自己玩的所以未做去敏，恕无法提供原始数据供以复现问题。

附错误输出
`Traceback (most recent call last):
  File "QQRecord2Excel.py", line 127, in <module>
  File "site-packages\pandas\core\ops\__init__.py", line 1229, in wrapper
  File "site-packages\pandas\core\ops\__init__.py", line 1091, in na_op
  File "site-packages\pandas\core\ops\__init__.py", line 1069, in _comp_method_OBJECT_ARRAY
  File "pandas/_libs/ops.pyx", line 96, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'str' and 'int'
[14636] Failed to execute script QQRecord2Excel`

**Comment by Dimsmary** [comment]
因为个人原因，目前我对该项目的更新已经搁置，近期可能不会进行更新。
你可以在源代码中添加打印命令来查看是哪一行的文本数据无法读取。
