### ISSUE TITLE
使用Coolq接口时报错

### ISSUE THREAD

**Issue by yuyi2439** [Dimsmary/Ossas_ChatBot#34]
由于coolq被封，所以我用的是[node-onebot](https://github.com/takayama-lily/oicq/tree/master/http-api)，不知道是不是node-onebot的问题

报错：

输入工作模式：3
Mon Jan 24 19:08:27 2022 开始监听Coolq/HTTP上报
{'self_id': 3495297353, 'time': 1643022537, 'post_type': 'message', 'message_type': 'group', 'sub_type': 'normal', 'message_id': 'OEEuQrCCrTcAAAEeS47XBGHuiMkB', 'group_id': 943795778, 'group_name': 'KucRobot官方群', 'user_id': 2961354039, 'anonymous': None, 'message': [{'type': 'at', 'data': {'qq': 3495297353, 'text': '@小楚妹妹'}}, {'type': 'text', 'data': {'text': ' 在？'}}], 'raw_message': '[CQ:at,qq=3495297353,text=@小楚妹妹] 在？', 'atme': True, 'block': False, 'seqid': 286, 'font': '微软雅黑', 'sender': {'user_id': 2961354039, 'nickname': '裕依', 'card': '', 'sex': 'male', 'age': 14, 'area': '徐州', 'level': 1, 'role': 'owner', 'title': ''}}
Traceback (most recent call last):
  File "main.py", line 117, in <module>
  File "main.py", line 48, in http_receive
AttributeError: 'list' object has no attribute 'find'
[17708] Failed to execute script main

**Comment by Misaka2298** [comment]
我也遇到了同样的问题
